### ISSUE TITLE
Thousands of byte read errors per week, spams logs but still functional

### ISSUE THREAD

**Issue by Robrowski** [Archef2000/homeassistant-upsplus#3]
It looks like the UPS is fully functional and I'm getting some data, but there are large gaps in the data and thousands of error logs. 

My installation is on a 
* Raspberry PI 4 with 8GB
* HA OS
* I'm also running another hat that should be using an entirely separate set of pins https://alarmdecoder.square.site/product/AD2pHAT/3?cs=true&cst=custom

HA splits the the logs into three groups:

```
Logger: homeassistant.helpers.entity
Source: custom_components/upsplus/battery.py:27
Integration: UPS I2C ([documentation](https://github.com/Archef2000/homeassistant-upsplus/blob/main/docs.md), [issues](https://github.com/Archef2000/homeassistant-upsplus/issues))
First occurred: August 21, 2023 at 10:26:13 AM (3986 occurrences)
Last logged: 4:00:35 PM

Update for sensor.ups_pi_report_voltage fails
Update for sensor.ups_battery_protection_voltage fails
Update for sensor.ups_input_report_voltage fails
Update for sensor.ups_battery_temperature fails
Update for sensor.ups_type_c_voltage fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 699, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/upsplus/sensor.py", line 69, in async_update
    state = read_buff(self._bus, *self._entity.get("index"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/upsplus/battery.py", line 27, in read_buff
    result = bus.read_byte_data(DEVICE_ADDR, index1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/smbus2/smbus2.py", line 433, in read_byte_data
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error
```

```
Logger: homeassistant.helpers.entity
Source: custom_components/upsplus/battery.py:31
Integration: UPS I2C ([documentation](https://github.com/Archef2000/homeassistant-upsplus/blob/main/docs.md), [issues](https://github.com/Archef2000/homeassistant-upsplus/issues))
First occurred: August 21, 2023 at 10:30:53 AM (5094 occurrences)
Last logged: 3:51:35 PM

Update for sensor.ups_running_time fails
Update for sensor.ups_battery_empty_voltage fails
Update for sensor.ups_processor_voltage fails
Update for sensor.ups_type_c_voltage fails
Update for sensor.ups_accumulated_running_time fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 699, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/upsplus/sensor.py", line 69, in async_update
    state = read_buff(self._bus, *self._entity.get("index"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/upsplus/battery.py", line 31, in read_buff
    result = result | bus.read_byte_data(DEVICE_ADDR, index) << (8 * i)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/smbus2/smbus2.py", line 433, in read_byte_data
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error
```

```
Logger: homeassistant.helpers.entity
Source: custom_components/upsplus/switch.py:37
Integration: UPS I2C ([documentation](https://github.com/Archef2000/homeassistant-upsplus/blob/main/docs.md), [issues](https://github.com/Archef2000/homeassistant-upsplus/issues))
First occurred: August 21, 2023 at 11:13:34 AM (171 occurrences)
Last logged: 3:19:59 PM

Update for switch.ups_turn_on_after_power_on fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 699, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/upsplus/switch.py", line 37, in async_update
    self._state = self._bus.read_byte_data(DEVICE_ADDR, 25) == 1
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/smbus2/smbus2.py", line 433, in read_byte_data
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error
```

**Comment by archef2000** [comment]
What firmware version does the ups have ?

**Comment by Robrowski** [comment]
I believe ``10``

**Comment by archef2000** [comment]
you can look in HA when you click on the UPS device in the integration

**Comment by Robrowski** [comment]
Yeah, it's 10

```
Device info
52Pi 18650 UPS
by 52PI
Firmware: 10
```

**Comment by archef2000** [comment]
Was the error since the beginning

**Comment by Robrowski** [comment]
I believe so, but I haven't found the logs to confirm. I installed the UPS in July or maybe in June and noticed the error logs back then and only got around to this now.

**Comment by archef2000** [comment]
It may need an update but as you are on HA OS it would be quite difficult i will update the integration to allow updates via the UI

**Comment by archef2000** [comment]
I have created a service to update the UPS read the [docs](https://github.com/archef2000/homeassistant-upsplus/blob/main/docs.md#updating-the-ups) and please update to  `v1.1.0` let me know if you need any further help

**Comment by archef2000** [comment]
I hope your issue has been resolved
